name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Aktualizacja do gałęzi master, której używasz w swoim repozytorium

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
      
      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # folder zawierający zbudowane pliki
          branch: gh-pages # gałąź, na którą będą wypychane zbudowane pliki